# 使用基础镜像
FROM ubuntu:20.04 as builder

# 安装需要的工具（curl, jq）
RUN apt-get update && \
    apt-get install -y curl jq && \
    apt-get clean

ARG GITHUB_OWNER=BeiDouMS
ARG GITHUB_REPO=BeiDou-Server
ARG ASSET_NAME_PREFIX=BeiDou-Server
ARG ASSET_NAME_EXT=tar.gz

# 获取最新 release 的 targz
RUN curl -s https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest \
    | jq -r '.assets[] | select(.name | endswith(".tar.gz")) | .browser_download_url' \
    | xargs -n 1 curl -fsSL -o latest_release.tar.gz

RUN mkdir -p /opt/server

RUN tar -xzvf latest_release.tar.gz -C /opt/server --strip-components=1

# alpine好像缺点东西
FROM ubuntu:20.04

WORKDIR /opt/server

COPY --from=builder /opt/server /opt/server

EXPOSE 8686 8484 7575 7576 7577

# 容器里就不用nohup了
# CMD ["sh" , "launch.sh"]
ENTRYPOINT ["./jdk-21.0.2/bin/java","-Dspring.config.location=application.yml","-jar","BeiDou.jar"]