FROM alpine AS codestage

RUN apk add --no-cache git 

WORKDIR /opt/repository

ARG CACHEBUST=1

RUN git clone https://github.com/BeiDouMS/BeiDou-Server --depth 1

FROM node:20 AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      optipng build-essential ca-certificates pkg-config libpng-dev zlib1g-dev python3 make gcc g++

WORKDIR /opt/ui

# for caching
COPY --from=codestage /opt/repository/BeiDou-Server/gms-ui/package.json ./
# for caching
COPY --from=codestage /opt/repository/BeiDou-Server/gms-ui/yarn.lock ./

RUN yarn global add yarn@v1.22.10 && \
    yarn install --frozen-lockfile --ignore-scripts && \
    PLATFORM=$(node -p "process.platform + '-' + process.arch") && \
    mkdir -p node_modules/optipng-bin/vendor/$PLATFORM && \
    ln -sf /usr/bin/optipng node_modules/optipng-bin/vendor/$PLATFORM/optipng

COPY --from=codestage /opt/repository/BeiDou-Server/gms-ui/ ./

RUN yarn build

FROM nginx:alpine

COPY --from=builder /opt/ui/dist/ /usr/share/nginx/html/

COPY ./nginx-ui.conf /etc/nginx/conf.d/default.conf

EXPOSE 8686
