name: BeiDou Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "no prefix release version"
        required: true
        type: string

    
env:
  GHCR_REGISTRY: ghcr.io
  RELEASE_IMAGE: beidou-server-all

jobs:
  Backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      # attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile-release
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ env.RELEASE_IMAGE }}:v${{ inputs.release_version }}
            ${{ env.GHCR_REGISTRY }}/${{ env.OWNER_LC }}/${{ env.RELEASE_IMAGE }}:v${{ inputs.release_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            RELEASE_VERSION=${{ inputs.release_version }}
  
    #   - name: Generate artifact attestation
    #     uses: actions/attest-build-provenance@v1
    #     with:
    #       subject-name: ${{ env.GHCR_REGISTRY }}/${{ env.OWNER_LC }}/${{ env.RELEASE_IMAGE }}
    #       subject-digest: ${{ steps.push.outputs.digest }}
    #       push-to-registry: true
