name: BeiDou Release Workflow

on:
  workflow_dispatch:
  # schedule:
  #   # 这个 cron 表达式表示每天的 21:00 UTC 触发
  #   - cron: '0 21 * * *'
    
env:
  REGISTRY: ghcr.io
  RELEASE_IMAGE: beidou-server-all

jobs:
  Backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      # attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-release-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-release-buildx-
      - name: get latest version
        run: |
          LATEST_RELEASE_VERSION=$(curl -fsSL https://api.github.com/repos/BeiDouMS/BeiDou-Server/releases/latest | jq -r '.name')
          echo "LATEST_RELEASE_VERSION=${LATEST_RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile-release
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.RELEASE_IMAGE }}:v${{ env.LATEST_RELEASE_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  
    #   - name: Generate artifact attestation
    #     uses: actions/attest-build-provenance@v1
    #     with:
    #       subject-name: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.RELEASE_IMAGE }}
    #       subject-digest: ${{ steps.push.outputs.digest }}
    #       push-to-registry: true
